### ISSUE TITLE
Flint throws error when reassigning const

### ISSUE THREAD

**Issue by asarode** [flintjs/flint-atom2#4]
The fint-atom package throws an error if you do something like:
```
const foo = 'bar'
foo = 'someting else'
```
It would be nicer if it prints out a nice error message saying you can't reassign a const variable. The other error messages are super nice so far by the way.

---

**Atom Version**: 1.2.0
**System**: Mac OS X 10.10.5
**Thrown From**: [flint](https://github.com/flintjs/flint-atom) package, v3.10.1

### Stack Trace

Uncaught TypeError: Cannot read property 'line' of undefined

```
At /Users/arjunsarode/.atom/packages/flint/lib/errors.js:23

TypeError: Cannot read property 'line' of undefined
    at /Users/arjunsarode/.atom/packages/flint/lib/errors.js:23:25
    at Array.map (native)
    at refresh (/Users/arjunsarode/.atom/packages/flint/lib/errors.js:20:35)
    at EventEmitter.<anonymous> (/Users/arjunsarode/.atom/packages/flint/lib/errors.js:32:40)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Object.onMessage (/Users/arjunsarode/.atom/packages/flint/lib/index.js:76:33)
    at WebSocket.connection.onmessage (/Users/arjunsarode/.atom/packages/flint/lib/bridge.js:32:10)
```

### Commands

```
     -0:18.6.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:14.1.0 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -0:14.1.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:13.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:11.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:11.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:11.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:11.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:11.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:11.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:05.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:05.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:04.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
atom-dark-fusion-syntax, v0.7.0
color-picker, v2.0.13
docblockr, v0.7.3
emmet, v2.3.14
flint, v3.10.1
floobits, v0.21.1
language-babel, v0.15.7
language-elixir, v0.5.2

# Dev
No dev packages
```

**Comment by natew** [comment]
@asarode thanks for the report, will look at this this week

**Comment by ncammarata** [comment]
![image](https://cloud.githubusercontent.com/assets/204989/11355253/6b27d85e-9208-11e5-9f22-69d36a769341.png)

Compiler errors are fixed and there's a nice error for consts now :)
